
zuul:
  routes:
    myproduct:
      path: /DProduct/**
      serviceId: product
      sensitiveHeaders:
  ignored-patterns:
      - /**/product/listForOrder
spring:
  rabbitmq:
    host: 192.168.17.128
    port: 5672
    username: guest
    password: guest
