spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yangheng
    url: jdbc:mysql://39.98.176.49:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

env:
  test3

girl:
  name: lili
  age: 998
