spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yangheng
    url: jdbc:mysql://39.98.176.49:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 192.168.17.128
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

env:
  test4

girl:
  name: lili
  age: 100
