spring:
  application:
    name: order
  
  rabbitmq:
    host: 192.168.17.128
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.17.128
    port: 6379

server:
  port: 8081

env:
  test120

girl:
  name: lili
  age: 100
