spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yangheng
    url: jdbc:mysql://39.98.176.49:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 192.168.17.128
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.17.128
    port: 6379

